### ISSUE TITLE
Remove "ember-release" from Travis build matrix

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-sort#64]
_.travis.yml_ file

```
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-release
  - node_js: 'stable'
```
